/**
 * Generates a per-job .sh script that the user downloads and runs locally.
 * The script bootstraps a Python venv, installs deps, then runs the full pipeline:
 *   yt-dlp download → Whisper → AI analysis → face crop → subtitle burn
 */

// Vite raw import — loads the Python file as a string at build time
import pythonContent from "./shortscut_pipeline.py?raw";

export interface JobScriptConfig {
  videoUrl: string;
  language: string;
  numShorts: number;
  minDuration: number;
  maxDuration: number;
  openaiApiKey?: string;
}

export function generateJobScript(config: JobScriptConfig): string {
  const { videoUrl, language, numShorts, minDuration, maxDuration, openaiApiKey } = config;

  // Escape single quotes for bash variables
  const esc = (s: string) => s.replace(/'/g, "'\\''");

  const apiKeyLine = openaiApiKey
    ? `export OPENAI_API_KEY='${esc(openaiApiKey)}'`
    : "# OPENAI_API_KEY not set — will prompt below";

  // Build the script as an array of lines for clarity
  const lines = [
    "#!/usr/bin/env bash",
    "# ═══════════════════════════════════════════════════════════════",
    "# ShortsCut — Podcast → YouTube Shorts (auto-generated job script)",
    "# ═══════════════════════════════════════════════════════════════",
    "#",
    "# Generated by ShortsCut. Run this script to process your video locally.",
    "#",
    "# Prerequisites: python3, ffmpeg (with libass), yt-dlp",
    '# Usage: chmod +x shortscut_job.sh && ./shortscut_job.sh',
    "# ═══════════════════════════════════════════════════════════════",
    "",
    "set -euo pipefail",
    "",
    "# ────────────── Job Configuration ──────────────",
    `VIDEO_URL='${esc(videoUrl)}'`,
    `LANGUAGE='${esc(language)}'`,
    `NUM_SHORTS=${numShorts}`,
    `MIN_DURATION=${minDuration}`,
    `MAX_DURATION=${maxDuration}`,
    apiKeyLine,
    "",
    'SHORTSCUT_DIR="$HOME/.shortscut"',
    'VENV_DIR="$SHORTSCUT_DIR/venv"',
    'PYTHON_SCRIPT="$SHORTSCUT_DIR/shortscut.py"',
    "",
    "RED='\\033[0;31m'",
    "GREEN='\\033[0;32m'",
    "YELLOW='\\033[1;33m'",
    "BLUE='\\033[0;34m'",
    "NC='\\033[0m'",
    "",
    'echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"',
    'echo -e "${BLUE}  🎬 ShortsCut — Podcast → YouTube Shorts${NC}"',
    'echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"',
    'echo ""',
    "",
    "# ────────────── Check prerequisites ──────────────",
    "check_command() {",
    '    if ! command -v "$1" &>/dev/null; then',
    '        echo -e "${RED}❌ \'$1\' not found.${NC}"',
    '        case "$1" in',
    '            python3) echo "   macOS: brew install python3  |  Linux: sudo apt install python3 python3-venv" ;;',
    '            ffmpeg)  echo "   macOS: brew install ffmpeg   |  Linux: sudo apt install ffmpeg" ;;',
    '            yt-dlp)  echo "   macOS: brew install yt-dlp   |  Linux: pip install yt-dlp" ;;',
    "        esac",
    "        exit 1",
    "    fi",
    "}",
    "",
    'echo -e "${YELLOW}🔍 Checking prerequisites...${NC}"',
    "check_command python3",
    "check_command ffmpeg",
    "check_command yt-dlp",
    "",
    "if ! ffmpeg -filters 2>/dev/null | grep -q \"subtitles\\\\|ass\"; then",
    '    echo -e "${YELLOW}⚠️  ffmpeg may not have libass. Subtitles might not burn correctly.${NC}"',
    '    echo "   macOS: brew install ffmpeg  |  Linux: sudo apt install ffmpeg libass-dev"',
    "fi",
    'echo -e "${GREEN}✅ Prerequisites OK${NC}"',
    "",
    "# ────────────── Check OpenAI API key ──────────────",
    'if [ -z "${OPENAI_API_KEY:-}" ]; then',
    '    echo ""',
    '    echo -e "${YELLOW}🔑 OpenAI API key needed for Whisper + GPT-4o.${NC}"',
    '    read -rp "   Enter your API key (sk-...): " user_key',
    '    if [ -z "$user_key" ]; then',
    '        echo -e "${RED}❌ No API key provided.${NC}"',
    "        exit 1",
    "    fi",
    '    export OPENAI_API_KEY="$user_key"',
    "fi",
    'echo -e "${GREEN}✅ API key set${NC}"',
    "",
    "# ────────────── Write Python pipeline ──────────────",
    'mkdir -p "$SHORTSCUT_DIR"',
    'echo -e "${YELLOW}📦 Setting up ShortsCut environment...${NC}"',
    "",
    "cat > \"$PYTHON_SCRIPT\" << 'PYTHON_HEREDOC_EOF'",
    pythonContent,
    "PYTHON_HEREDOC_EOF",
    "",
    'chmod +x "$PYTHON_SCRIPT"',
    "",
    'echo ""',
    'echo -e "${BLUE}▶ Starting pipeline for:${NC}"',
    'echo -e "  ${BLUE}URL:${NC}      $VIDEO_URL"',
    'echo -e "  ${BLUE}Language:${NC}  $LANGUAGE"',
    'echo -e "  ${BLUE}Shorts:${NC}   $NUM_SHORTS (${MIN_DURATION}s–${MAX_DURATION}s)"',
    'echo ""',
    "",
    'exec python3 "$PYTHON_SCRIPT" "$VIDEO_URL" \\',
    '    --api-key "$OPENAI_API_KEY" \\',
    '    --language "$LANGUAGE" \\',
    '    --num-shorts "$NUM_SHORTS" \\',
    '    --min-duration "$MIN_DURATION" \\',
    '    --max-duration "$MAX_DURATION"',
  ];

  return lines.join("\n") + "\n";
}

/**
 * Triggers a browser download of the generated script.
 */
export function downloadScript(config: JobScriptConfig, filename: string = "shortscut_job.sh") {
  const content = generateJobScript(config);
  const blob = new Blob([content], { type: "application/x-sh" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
